### ISSUE TITLE
Response data comes in small/short chunks making it hard to read

### ISSUE THREAD

**Issue by jgphilpott** [jgphilpott/polyslice#1]
### Description:

With some machines, the response data comes in small/short chunks making it hard to read in the output log. See [this comment](https://github.com/sir-buckyball/chrome-gcode-sender/issues/57#issuecomment-2073481688) by @moof-moof for more detail.

### Reproduction:

The ability to reproduce this issue will depend on what machine you are using but in general, follow these steps:

- Connect to the device.
- Send some sample G-code commands.
- Observe the output log.

### Expected Behavior:

The output contains longer more readable text.

### Screenshots:

See [here](https://github.com/sir-buckyball/chrome-gcode-sender/issues/57#issuecomment-2073481688).

### Environment:

Please include the following information:

 - **Device**: Custom 2D CNC machine with an Arduino Uno
 - **Firmware**: GRBL
 - **OS**: Linux Ubuntu 20.04
 - **Browser**: Chrome 
 - **Version**: 124.0.6367.60

### Extra:

Add any other information about the problem here.

**Comment by jgphilpott** [comment]
@moof-moof my best guess is that it has something to do with the [connection settings](https://developer.mozilla.org/en-US/docs/Web/API/SerialPort/open#parameters), most likely the [buffer size](https://developer.mozilla.org/en-US/docs/Web/API/SerialPort/open#buffersize). The docs I linked to should provide more detail on each of the settings. You should be able to edit each of the settings using the inputs at the top of the page (see screenshot 1). Modifying any of the settings will automatically disconnect you from the machine so be sure to reconnect afterwards.

Perhaps try Googling the recommended connection settings for your machine? I've noticed that I occasionally get broken response data from my printer but not all the time and the messages are always longer than 4 characters (see screenshot 2). Without having access to your device it's a little hard to debug, how about you try fiddling with your connection settings and if it's still not working I will take a closer look over the weekend when I have more time.

If you want to see the raw response data in the console try adding `console.log(decoder.decode(value))` to line `147` of `serial/browser/sender.js`.

**Screenshot 1**

<img width="1013" alt="Screenshot 2024-04-24 at 3 08 07 PM" src="https://github.com/jgphilpott/polyslice/assets/4128208/201e7612-01a8-4afe-a929-c37d688dde9b">

**Screenshot 2**

<img width="1434" alt="Screenshot 2024-04-24 at 3 16 31 PM" src="https://github.com/jgphilpott/polyslice/assets/4128208/f036f3ad-2144-417c-b575-4da819c71d3d">

**Comment by jgphilpott** [comment]
FYI @moof-moof I think I've got a solution for this, I'm working on it and will update you shortly.

**Comment by jgphilpott** [comment]
Hey @moof-moof I believe I have a solution that should work regardless of the connection settings. If you could checkout the **[bug/1/response-data-comes-in-small-chunks-making-it-hard-to-read](https://github.com/jgphilpott/polyslice/tree/bug/1/response-data-comes-in-small-chunks-making-it-hard-to-read)** branch and let me know if it is working for you that would be awesome! The branch also contains a few other small changes I made so if you want to see the fix for just this issue take a look at [this commit](https://github.com/jgphilpott/polyslice/commit/459fc718550d544e4147754556f48ef911d1f609). Once you can confirm it's working (or not) I will merge the changes into the `main` branch.

**Comment by moof-moof** [comment]
Hey-hey-hey! @jgphilpott    
"S-U-C-C-E-S-S" -- That is how we spell success!
Thank you for your help.
